# Generated by Django 6.1.1 on 2026-09-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_department_project_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['joining_date'], name='employees_e_joining_69a338_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'is_active'], name='employees_e_departm_fa1d35_idx'),
        ),
    ]
