# Generated by Django 6.1.1 on 2026-09-29 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_employees_e_joining_69a338_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('transferred_by', models.CharField(blank=True, max_length=100)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_history', to='employees.employee')),
                ('from_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='employees.department')),
                ('to_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='employees.department')),
            ],
            options={
                'ordering': ['-transferred_at'],
                'indexes': [models.Index(fields=['employee', 'transferred_at'], name='employees_e_employe_f2dae1_idx'), models.Index(fields=['from_department'], name='employees_e_from_de_d250b4_idx'), models.Index(fields=['to_department'], name='employees_e_to_depa_63b288_idx'), models.Index(fields=['status'], name='employees_e_status_f85164_idx')],
            },
        ),
    ]
